Resolução dos Exercícios Letícia
desenvolve-gb-turma2/python pull request #12
Opened 2023-03-08 13:43 UTC by Leticia-Souza94

Minha resolução para os exercícios 01-fibonacci e 03-LEDS

2023-03-10 02:09 UTC, venezianluis commented
Oi Letícia, tem dois pontos pra eu comentar aqui antes de iniciar os reviews:

- O primeiro é uma falha que partiu da minha explicação que não detalho o seguinte: pra que a gente se organize melhor o ideal é que cada pull request contemple apenas uma solução, vamos combinar de deixar esse passar, pois existem outras pessoas fazendo assim também, só alerto para que possamos seguir no modelo 1 pull pra cada solução daqui pra frente. :)
- Outro ponto: é que nos seus commits você está removendo um arquivo que não tem relação com sua alteração, no caso o arquivo da minha solução do exercício de fibonacci, como era um desafio teste também passará, entretanto, no próximo exercício revise as alterações que está commitando para não acontecer novamente.

Acredito que esse final de semana consigo revisar tudo e fazer o merge.

2023-03-10 15:46 UTC, Leticia-Souza94 commented
Olá, Luis. Agradeço o feedback e a paciência. 

Vou seguir dessa forma então, realizando apenas 1 pull para cada solução. 
Sobre a remoção do seu arquivo eu não sei como fiz isso, mas me lembro que em algumas ocasiões no momento do commit tinham arquivos com um sinal de - em vermelho e um com sinal de + em verde. Nesse momento eu posso ter substituído algo?  

Obrigado!

2023-03-17 19:23 UTC, MiuraBruno reviewed
Olá @Leticia-Souza94 , se eu entendi certo na aba files changed o + verde indica inclusão e o - vermelho indica remoção em relação a branch main sejam arquivos pastas ou linhas

2023-03-22 22:57 UTC, venezianluis requested changes
Por gentielza resolver a questão das entradas negativas com falha para o caso do fibonacci

2023-03-22 22:57 UTC, venezianluis commented on solucoes/Leticia-Souza94/01-fibonacci/Resolução-fibonacci.py
Precisa validar apenas mais uma coisa: permitir apenas entradas > 0
![image](https://user-images.githubusercontent.com/36893796/227056105-bbb0e9e8-0d90-48fe-81fc-63926b17e864.png)

2023-03-22 22:57 UTC, venezianluis commented on solucoes/Leticia-Souza94/03-LEDS/Resolução-LEDS.py
> +print("Obrigado por utilizar nosso programa!")
Isso não é um problema funcional, mas para manter um código limpo vamos deixar prints restritos a mensagens que são de instrução ou log :)

2023-03-27 16:46 UTC, MiuraBruno commented on solucoes/Leticia-Souza94/03-LEDS/Resolução-LEDS.py
Muito bem, o código enviado funciona perfeitamente.

de uma olhada depois da solução que eu fiz e compare com a sua.

lembrando que o objetivo era consequir fazer então está ótimo :) e existem inumeras formas de se fazer a mesma coisa

2023-03-27 16:47 UTC, MiuraBruno reviewed
comentários sobre LEDs

2023-03-29 14:11 UTC, Leticia-Souza94 commented on solucoes/Leticia-Souza94/03-LEDS/Resolução-LEDS.py
Muito obrigado. Feliz que deu certo !!!

2023-05-19 18:29 UTC, merged