Minha resolução do desafio
desenvolve-gb-turma2/python pull request #2
Opened 2023-03-02 20:27 UTC by mateusap

2023-03-02 21:32 UTC, MiuraBruno requested changes
Seu código retornou o valor 1 para todos os casos que eu testei
<img width="639" alt="Captura de Tela 2023-03-02 às 18 32 02" src="https://user-images.githubusercontent.com/40796611/222560073-6e42ab07-e7fe-4b45-b4f0-360c28896ad6.png">

2023-03-03 02:28 UTC, MiuraBruno reviewed
teste

2023-03-03 12:32 UTC, venezianluis commented
@mateusap 

input: `fibonacci(-1) `
output: `[1, 1]`

2023-03-03 12:43 UTC, mateusap commented
Não consigo fazer commit das alterações desde o primeiro pull request, mas pra resolver esse problema eu precisaria adicionar essa parte
"elif e <= 0:
        return "Fibonacci não trabalha com números negativos""

2023-03-05 16:43 UTC, venezianluis approved these changes

2023-03-05 16:44 UTC, venezianluis commented
Por mim aprovado, fiz os testes na máquina local e deu certo, falta o @MiuraBruno validar

2023-03-10 16:44 UTC, MiuraBruno approved these changes

2023-03-10 16:44 UTC, merged